#%RAML 0.8
baseUri: https://healthcare-ehr2fhir-patient-process-api.cloudhub.io/api
title: healthcare-ehr2fhir-patient-process-api
mediaType: application/json
version: v1
securedBy: [basic]
securitySchemes:
 - basic:
    description: |
      This API supports Basic Authentication.
    type: Basic Authentication
/patients/{patientIDType}/{patientID}:
  displayName: patient
  uriParameters:
    patientID:
      type: string
      description: Patient ID
    patientIDType:
      type: string
      description: ID Type like MRN
  get:
    description: Get Patient information - FHIR
    responses:
      200:
        body:
          application/json:
            example: !include patient-fhir-response.json
  put:
    description: Updates Patient information - FHIR
    body: 
      application/json:
        example: !include patient-fhir-body.json
    responses:
      204: