#%RAML 1.0 DataType

#This file is located at dataTypes/SuccessResponse.raml

type: object
properties:
  id: string
  message: string
example:
  id: asdhak123123123
  message: Registration completed successfully. You can log in with your credentials. 